# Generated by Django 2.2.12 on 2020-04-26 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='latlon',
            new_name='point',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='latlon',
            new_name='point',
        ),
    ]
