# Generated by Django 2.2.12 on 2020-04-29 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='photos',
            field=models.ManyToManyField(related_name='_photos', through='location.NoticePhoto', to='media.Photo'),
        ),
    ]
