# Generated by Django 2.2.12 on 2020-04-27 18:32

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_nearbysearch'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='external_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='location',
            name='external_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
