# Generated by Django 2.2.12 on 2020-04-27 19:13

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_auto_20200427_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=256)),
                ('result', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='city',
            name='external_data',
        ),
        migrations.RemoveField(
            model_name='location',
            name='external_data',
        ),
    ]
