# Generated by Django 2.2.12 on 2020-05-01 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_auto_20200429_1813'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ('-updated',)},
        ),
    ]
