# Generated by Django 2.2.12 on 2020-05-01 14:40

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_auto_20200501_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='datasource',
            field=models.CharField(blank=True, choices=[['exif', 'exif']], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
