# Generated by Django 2.2.12 on 2020-05-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0005_auto_20200501_1440'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ('-datetime',)},
        ),
        migrations.AlterField(
            model_name='photo',
            name='datasource',
            field=models.CharField(blank=True, choices=[['exif', 'exif'], ['exifgps', 'exifgps'], ['database', 'database'], ['error', 'error']], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='src',
            field=models.ImageField(upload_to='photo'),
        ),
    ]
